# -*- coding: utf-8 -*-
"""Konversi-Model-FS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eW6L7L6igGP2m14asQDr_BDTtZSJjDSm

# **Import Library**
"""

from google.colab import drive
drive.mount('/content/drive')

# Downgrade agar tidak conflict dengan tfjs
!pip install packaging==23.1 -q

!pip install tensorflow==2.18.0 tensorflowjs -q

import tensorflow as tf
import os
import shutil
import zipfile

"""# **Load Model**"""

model_path = '/content/drive/MyDrive/Hijabist-Drive/Face-shape/Model keras/Face-shape-model.keras'

# Load model
model = tf.keras.models.load_model(model_path)

model.summary()

"""# **Konversi ke Saved_model**"""

# Konversi ke Saved_Model
model.export('/content/saved_model_FS/1')

!zip -r saved_model_FS.zip /content/saved_model_FS

"""# **Konversi ke TFJS**"""

# Konversi Saved_Model ke TensorFlow.js
!tensorflowjs_converter \
    --input_format=tf_saved_model \
    /content/saved_model_FS/1 \
    /content/modeltfjs_FS

print("Model berhasil dikonversi ke TensorFlow.js.")

!zip -r model_tfjs_FS.zip /content/modeltfjs_FS

"""# **Konversi ke TFlite (Opsional)**"""

# Konversi Saved_Model ke format TFLite
save_path = '/content/saved_model_FS/1'
converter = tf.lite.TFLiteConverter.from_saved_model(save_path)
tflite_model = converter.convert()
with tf.io.gfile.GFile('/content/model_FS.tflite', 'wb') as f:
    f.write(tflite_model)

print("Model berhasil dikonversi ke TFLite dan disimpan sebagai model_FS.tflite")

"""# **Copy to drive**"""

# Definisikan path ke file zip
files_to_copy = ["saved_model_FS.zip", "model_tfjs_FS.zip", "model_FS.tflite"]

# Inisialisasi folder Google Drive
destination_folder = '/content/drive/MyDrive/Hijabist-Drive/Face-shape/Model-Convert/'
os.makedirs(destination_folder, exist_ok=True)

# Salin setiap file zip ke Google Drive
for zip_file_path in files_to_copy:
  destination_path = os.path.join(destination_folder, os.path.basename(zip_file_path))
  try:
    shutil.copy(zip_file_path, destination_path)
    print(f"'{zip_file_path}' disalin ke '{destination_path}'")
  except FileNotFoundError:
    print(f"Error: '{zip_file_path}' tidak ditemukan.")
  except Exception as e:
    print(f"Terjadi error saat menyalin '{zip_file_path}': {e}")